### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by localstars-ltd** [PolymerLabs/polyup#105]
Hi all,

firstly if this is in the wrong place I apologize! 

However I am not able to install via:

npm install -g polyup
npm i -g polyup
npm i -g polyup --force

or any combination of

I have set all SSL conf as per the npm docs, I get the following:

 ```
C:\Users\jason.lane>npm i -g polyup
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git+https://github.com/rictic/estree-walker.git#distrib resetting remote C:\Users\jason.lane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-rictic-es
tree-walker-git-distrib-3ec9ce48c553e4961f20978556407fc4 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\jason.lane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/rictic/estree-walker.git C:\Users\jason.lane\AppData\Roam
ing\npm-cache\_git-remotes\git-https-github-com-rictic-estree-walker-git-distrib-3ec9ce48c553e4961f20978556407fc4: Cloning into bare repository 'C:\Users\jason.lane\AppData\Roaming\npm-
cache\_git-remotes\git-https-github-com-rictic-estree-walker-git-distrib-3ec9ce48c553e4961f20978556407fc4'...
npm ERR! git clone --template=C:\Users\jason.lane\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/rictic/estree-walker.git C:\Users\jason.lane\AppData\Roam
ing\npm-cache\_git-remotes\git-https-github-com-rictic-estree-walker-git-distrib-3ec9ce48c553e4961f20978556407fc4: fatal: unable to access 'https://github.com/rictic/estree-walker.git/'
: SSL certificate problem: self signed certificate in certificate chain
npm WARN install Couldn't install optional dependency: Command failed: git -c core.longpaths=true clone --template=C:\Users\jason.lane\AppData\Roaming\npm-cache\_git-remotes\_templates
--mirror https://github.com/rictic/estree-walker.git C:\Users\jason.lane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-rictic-estree-walker-git-distrib-3ec9ce48c553e4961f2
0978556407fc4
npm WARN install Cloning into bare repository 'C:\Users\jason.lane\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-rictic-estree-walker-git-distrib-3ec9ce48c553e4961f2097855
6407fc4'...
npm WARN install fatal: unable to access 'https://github.com/rictic/estree-walker.git/': SSL certificate problem: self signed certificate in certificate chain
npm WARN install
```

Interestingly doing npm install -g estree-walker gives:

```
C:\Users\jason.lane>npm install -g estree-walker
C:\Users\jason.lane\AppData\Roaming\npm
└── estree-walker@0.1.3
```

npm is at version 3.3.8 & node 4.2.1

Many thanks

**Comment by davidmaxwaterman** [comment]
(Caveat: I notice you're on MS Windows - not sure of any specifics there). Are you behind some kind of firewall?

**Comment by rictic** [comment]
David's right, this sounds like you're behind a MITM SSL proxy. If this machine is part of an institution (company, school, etc) then you'll need to take it up with the network admin.

If not, I'd recommend looking under npm's docs. Similar issues: https://github.com/npm/npm/issues/7519
and https://github.com/npm/npm/issues/9282
