### ISSUE TITLE
Polyup crashes inserting warning about being unable to infer the components dir.

### ISSUE THREAD

**Issue by ktiedt** [PolymerLabs/polyup#13]
I am hoping there is maybe something I am missing to make this more meaningful? I have an html file (several actually) that if I run polyup against and I get this output

```
polyup --overwrite main.html
Error attempting to upgrade main.html


/usr/local/lib/node_modules/polyup/lib/node_main.js:55
  throw e;
        ^
TypeError: Cannot read property 'previousSibling' of undefined
    at insertHtmlCommentBefore (/usr/local/lib/node_modules/polyup/lib/upgrade_html.js:580:11)
    at addHtmlImport (/usr/local/lib/node_modules/polyup/lib/upgrade_html.js:685:5)
    at upgradeGlobalCss (/usr/local/lib/node_modules/polyup/lib/upgrade_html.js:612:5)
    at upgradeHtml (/usr/local/lib/node_modules/polyup/lib/upgrade_html.js:47:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/polyup/lib/node_main.js:52:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by rictic** [comment]
Thanks for the report! Yep, that's a bug. Ironically, it looks like it's in some error handling code.

Should be fixed by #14

You can give it a shot by running `npm install -g PolymerLabs/polyup#warn-no-components-dir`

**Comment by ktiedt** [comment]
Thanks, will give it a go Monday since it is a work related project.

**Comment by yonathan9669** [comment]
Hi, 

The most of the elements that i need to migrate, break with an error like that.
But there are more than a few of those, i'll put some of them if that help you.

```
/usr/local/lib/node_modules/polyup/lib/node_main.js:55
  throw e;
        ^
TypeError: Cannot read property 'match' of undefined
    at /usr/local/lib/node_modules/polyup/lib/upgrade_html.js:455:40
    at Array.forEach (native)
    at upgradeDataBoundTemplate (/usr/local/lib/node_modules/polyup/lib/upgrade_html.js:451:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/polyup/lib/upgrade_html.js:136:5)
    at exports.each (/usr/local/lib/node_modules/polyup/node_modules/whacko/lib/api/traversing.js:294:24)
    at upgradeHtml (/usr/local/lib/node_modules/polyup/lib/upgrade_html.js:49:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/polyup/lib/node_main.js:52:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
```
/usr/local/lib/node_modules/polyup/lib/node_main.js:55
  throw e;
        ^
Error: Line 1: Unexpected token }
    at throwError (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:2070:17)
    at throwUnexpected (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:2133:5)
    at expect (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:2142:9)
    at parseGroupExpression (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:2814:5)
    at parsePrimaryExpression (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:2830:16)
    at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:2995:57)
    at parsePostfixExpression (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:3044:12)
    at parseUnaryExpression (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:3104:16)
    at parseBinaryExpression (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:3196:12)
    at parseConditionalExpression (/usr/local/lib/node_modules/polyup/node_modules/espree/espree.js:3257:12)
```
```
/usr/local/lib/node_modules/polyup/lib/node_main.js:55
  throw e;
        ^
TypeError: Cannot read property 'leadingComments' of undefined
    at /usr/local/lib/node_modules/polyup/lib/upgrade_js.js:380:34
    at Array.forEach (native)
    at /usr/local/lib/node_modules/polyup/lib/upgrade_js.js:375:17
    at Array.forEach (native)
    at /usr/local/lib/node_modules/polyup/lib/upgrade_js.js:363:27
    at Array.forEach (native)
    at migrateAttributesToPropertiesBlock (/usr/local/lib/node_modules/polyup/lib/upgrade_js.js:352:26)
    at /usr/local/lib/node_modules/polyup/lib/upgrade_js.js:97:5
    at Array.forEach (native)
    at upgradeJs (/usr/local/lib/node_modules/polyup/lib/upgrade_js.js:44:16)
```

As an advice, i believe the codes like this
```<select value="{{ timeCondition }}" on-change="{{onTimeConditionChange}}">...</select>```
could cause one or some of the issues, because in all the elements i have a "select" tag, that element can't be upgrade (throw an exception).

**Comment by rictic** [comment]
Should be fixed, let me know if you continue to see crashes.
