### ISSUE TITLE
Support template strings in components

### ISSUE THREAD

**Issue by mrdewitt** [PolymerLabs/polyup#75]
Got the following stack trace when upgrading a component with an ES6 template string (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings)

Error: Line 20: Unexpected token ILLEGAL
    at throwError (polyup/node_modules/espree/espree.js:2075:17)
    at scanPunctuator (polyup/node_modules/espree/espree.js:646:5)
    at advance (polyup/node_modules/espree/espree.js:1424:12)
    at lex (polyup/node_modules/espree/espree.js:1478:74)
    at parseAssignmentExpression (polyup/node_modules/espree/espree.js:3561:17)
    at parseExpression (polyup/node_modules/espree/espree.js:3573:16)
    at parseStatement (polyup/node_modules/espree/espree.js:4339:12)
    at parseSourceElement (polyup/node_modules/espree/espree.js:5181:16)
    at parseFunctionSourceElements (polyup/node_modules/espree/espree.js:4419:25)
    at parseFunctionExpression (polyup/node_modules/espree/espree.js:4667:12)

I believe espree supports template strings via a config option, but they are default disabled.

**Comment by mrdewitt** [comment]
An example of a file that causes this exception:

https://code.google.com/p/chromium/codesearch#chromium/infra/appengine/sheriff_o_matic/ui/ct-failure-stream.html

**Comment by rictic** [comment]
Please file any other ES6 bugs you come across as well! The main class of bugs that I can forsee will be with missing the new ways to declare functions and properties on object literals.
