### ISSUE TITLE
Failing with cryptic error message

### ISSUE THREAD

**Issue by danielbaak** [PolymerLabs/polyup#93]
Maybe I'm being too picky, but it would help if polyup could at least point at the line in which it couldn't handle something.

Running polyup on https://github.com/stevenrskelton/sortable-table yields the following output:
```
polyup sortable-table.html 
Error attempting to upgrade sortable-table.html



/home/user/.npm-packages/lib/node_modules/polyup/dist/node_main.js:111
  throw e;
        ^
Error: Line 1: Unexpected identifier
    at throwError (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:2070:17)
    at throwUnexpected (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:2115:9)
    at consumeSemicolon (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:2214:9)
    at parseStatement (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:4361:5)
    at parseSourceElement (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:5187:16)
    at parseSourceElements (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:5220:25)
    at parseProgram (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:5240:12)
    at Object.parse (/home/user/.npm-packages/lib/node_modules/polyup/node_modules/espree/espree.js:5483:19)
    at matchFirstExpression (/home/user/.npm-packages/lib/node_modules/polyup/dist/upgrade_html.js:669:46)
    at Page.matchExpressions (/home/user/.npm-packages/lib/node_modules/polyup/dist/upgrade_html.js:698:23)
```

**Comment by rictic** [comment]
This is true, we can do way better. I'll take a look at this now.

**Comment by rictic** [comment]
With the linked PR the error message is now:

```
Error: 
Unable to parse:   observing(forceFilterRefresh) as columns
inside of expression:   {{columns | observing(forceFilterRefresh) as columns}}
in file:   /Users/rictic/open/sortable-table/sortable-table.html

Parse error: Line 1: Unexpected identifier
```

Which is happening because polyup doesn't know about `<template bind>`. Filed as #94
